name = "AdventOfCode2025"
version = "0.1.0"
defaultTargets = ["adventofcode2025"]

[[lean_lib]]
name = "AdventOfCode2025"

[[lean_exe]]
name = "adventofcode2025"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"